//导航下拉列表
$("#mous").mouseenter(function(){
	$(".redbox").slideDown(200);
});
$("#mous").mouseleave(function(){
	$(".redbox").slideUp(200);
});
$("#mous-1").mouseenter(function(){
	$(".redbox-2").slideDown(200);
});
$("#mous-1").mouseleave(function(){
	$(".redbox-2").slideUp(200);
});
$("#mous-2").mouseenter(function(){
	$(".redbox-3").slideDown(200);
});
$("#mous-2").mouseleave(function(){
	$(".redbox-3").slideUp(200);
});
$("#mous-3").mouseenter(function(){
	$(".redbox-4").slideDown(200);
});
$("#mous-3").mouseleave(function(){
	$(".redbox-4").slideUp(200);
});
$("#mous-4").mouseenter(function(){
	$(".redbox-5").slideDown(200);
});
$("#mous-4").mouseleave(function(){
	$(".redbox-5").slideUp(200);
});
$("#mous-5").mouseenter(function(){
	$(".redbox-6").slideDown(200);
});
$("#mous-5").mouseleave(function(){
	$(".redbox-6").slideUp(200);
});
